main_site/urls.py
from django.conf.urls import include,url
from django.contrib import admin

urlpatterns = [
#    url(r'^ng/', include('ng.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^', include('ng.urls')),
]

handler400 = "ng.views.error"
handler403 = "ng.views.error"
handler404 = "ng.views.error"
handler500 = "ng.views.error"

ng/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.conf.urls import handler404, handler500
import django

from . import views

from django.views.generic.base import RedirectView

favicon_view = RedirectView.as_view(url='/static/ng/img/favicon.ico', permanent=True)


app_name = 'ng'
urlpatterns = [
    url(r'^favicon\.ico$', favicon_view),
    #url(r'^index/$', views.IndexView.as_view(), name='index'),
    url(r'^new_experiment/$', views.new_experiment, name='new_experiment'),
    #url(r'^choose_experiment/$', views.choose_experiment, name='choose_experiment'),
    url(r'^new_experiment/(?P<xp_cfg_name>[0-9a-z]+)$', views.new_experiment, name='new_experiment_cfg'),
    #url(r'^(?P<xp_uuid>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/$', views.DetailView.as_view(), name='detail'),
    #url(r'^(?P<xp_uuid>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/$', views.exp_resume, name='exp_resume'),
    ##  url(r'^(?P<xp_uuid>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/results_srtheo/$', views.result_srtheo, name='results_srtheo'),#ResultsView.as_view(), name='results'),
    #url(r'^(?P<xp_uuid>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})-hearer-(?P<meaning>[0-9a-z]+)/results/$', views.result_hearer, name='results_hearer'),#ResultsView.as_view(), name='results'),
    #url(r'^(?P<xp_uuid>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})-speaker-(?P<meaning>[0-9a-z]+)-(?P<word>[0-9a-z]+)/results/$', views.result_speaker, name='results_speaker'),#ResultsView.as_view(), name='results'),
    url(r'^(?P<xp_uuid>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})-hearer-$', views.result_hearer, name='results_hearer_base'),#ResultsView.as_view(), name='results'),
    url(r'^(?P<xp_uuid>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})-speaker-$', views.result_speaker, name='results_speaker_base'),#ResultsView.as_view(), name='results'),
    url(r'^(?P<xp_uuid>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/continue/$', views.continue_userxp, name='continue'),
    #url(r'^accounts/login/$', django.contrib.auth.views.login,name='login_old'),
    url(r'^logout/$', django.contrib.auth.views.logout, {'next_page': '/login'}, name='logout'),
    #url(r'^login/$', views.login_view, name='login'),
    url(r'^login/$', views.get_name, name='login'),

    #url(r'^(?P<xp_uuid>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})-hearer-(?P<meaning>[0-9a-z]+)/results_json/$', views.result_hearer_json, name='results_hearer_json'),#ResultsView.as_view(), name='results'),

    #url(r'^(?P<xp_uuid>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})-speaker-(?P<meaning>[0-9a-z]+)-(?P<word>[0-9a-z]+)/results_json/$', views.result_speaker_json, name='results_speaker_json'),#ResultsView.as_view(), name='results'),

    url(r'^(?P<xp_uuid>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})-hearer-(?P<meaning>[0-9a-z]+)/results_continue/$', views.result_hearer_continue, name='results_hearer_continue'),#ResultsView.as_view(), name='results'),
    url(r'^(?P<xp_uuid>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})-speaker-(?P<meaning>[0-9a-z]+)-(?P<word>[0-9a-z]+)/results_continue/$', views.result_speaker_continue, name='results_speaker_continue'),#ResultsView.as_view(), name='results'),

    #url(r'^results_inner/(?P<xp_uuid>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/(?P<bool_succ>(True|False))/$', views.result_inner, name='results_inner'),#ResultsView.as_view(), name='results'),
    #url(r'^results_inner/(?P<xp_uuid>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/$', views.result_inner, name='results_inner_base'),#ResultsView.as_view(), name='results'),
     #url(r'^(?P<xp_uuid>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})-speaker-(?P<meaning>[0-9a-z]+)-(?P<word>[0-9a-z]+)/results_json/$', views.result_speaker_json, name='results_speaker_json'),#ResultsView.as_view(), name='results'),


    url(r'^$',views.home,name='home'),

    ## url(r'^test/$',views.test,name='test'),
    #url(r'^accounts/profile/$', views.new_experiment, name='new_experiment_2'),
    #url(r'^accounts/login/$', auth_views.LoginView.as_view()),

    ## url(r'^userinfo_$', views.none, name='send_user_info_base'),
    ## url(r'^userinfo_(?P<username>[\w-]+)$', views.create_and_login, name='send_user_info'),

	######
	url(r'^story$', views.story, name='story'),
	url(r'^(?P<xp_uuid>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/results', views.score, name='results'),
    url(r'^infos', views.info, name='info'),

    # ###DEBUG###
    #
    # url(r'^test_score', views.test_score, name='test_score'),
    # url(r'^test_infos', views.test_info, name='test_info'),
    # url(r'^error', views.error, name="error"),
]

ng/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.db.models.signals import post_save

from django.utils.timezone import now

import naminggamesal as ngal

# Create your models here.

import json
import pickle
import random
import datetime
import copy

xp_cfg = {
    "step": 1,
    "pop_cfg": {
        "voc_cfg": {
            "voc_type": "2dictdict"
        },
        'agent_init_cfg':{
            'agent_init_type':'oneuser_noninteractive',
        },
        "strat_cfg": {
            "vu_cfg": {
                "vu_type": "minimalsynonly"
            },
            "success_cfg": {
                "success_type": "global"
            },
            "strat_type": "naive",
            "allow_idk":True,
        },
        "nbagent": 5,
        "env_cfg": {
            "env_type": "simple_realwords",
            "M": 5,
            "W": 6
        },
        "interact_cfg": {
            "interact_type": "speakerschoice"
        }
    }
}

null_date = None
MEANING_LIST = list(range(13))

#extended User class
class UserNG(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key = True)
    lang = models.CharField(max_length=3, default="en")
    #ID for certain types of Users
    code = models.CharField(max_length=100, null=True, blank= True, default='prolific')
    last_xp = models.CharField(max_length=100, null=True, blank= True, default='')
    #Number of games played, used as condition for unlocking game modes
    tuto_played = models.BooleanField(default=False)
    nbr_played = models.IntegerField(default=0)
    nbr_won = models.IntegerField(default=0)
    use_matomo = models.BooleanField(default=True)
    prolific_user = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    #Has the user seen the informations displayed after 3 games ?
    q_seen = models.BooleanField(default=False)
    q_seen_at = models.DateTimeField(blank=True,null=True,default=null_date)

    #Has the user already filled the form ?
    q_filled = models.BooleanField(default=False)

    #Questions
    q0 =  models.IntegerField(default=-2)
    q1 =  models.BooleanField(default=False)
    q2 =  models.BooleanField(default=False)
    q3 =  models.BooleanField(default=False)
    q4 =  models.BooleanField(default=False)
    q5 = models.TextField(null=True, blank= True, default='')
    q6 = models.TextField(null=True, blank= True, default='')

    def __str__(self):
        return self.user.username

    @property
    def first_name(self):
        return self.user.first_name


    @classmethod
    def get(cls,user):
        try:
            user_ng = cls.objects.get(user=user)
        except cls.DoesNotExist:
            user_ng = cls.objects.create(user=user)
            user_ng.save()
        return user_ng

    def update_nbr_played(self):
        self.nbr_played = len(Experiment.objects.filter(xp_config__xp_cfg_name="normal",user=self.user,is_complete=True))
        self.nbr_won = len(Experiment.objects.filter(xp_config__xp_cfg_name="normal",user=self.user,game_won=True))
        self.save()

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created :
        UserNG.objects.create(user=instance)


class Word(models.Model):
    word = models.CharField(max_length=200,unique=True)
    #experiment = models.ManyToManyField(Experiment,null=True)
    def __str__(self):
        return self.word

class Role(models.Model):
    role = models.CharField(max_length=10,unique=True)
    def __str__(self):
        return self.role

class Meaning(models.Model):
    #experiment = models.ManyToManyField(Experiment,null=True)
    #meaning = models.IntegerField()
    meaning = models.CharField(max_length=100,unique=True)
    def __str__(self):
        return self.meaning

    @classmethod
    def get_mlist(cls,M=None,avoid_if_possible=[]):
        m_l = copy.deepcopy(MEANING_LIST)
        for m_av in avoid_if_possible:
            if (M is None or len(m_l) > M) and m_av in m_l:
                m_l.remove(m_av)
        random.shuffle(m_l)
        return m_l[:M]


class XpConfig(models.Model):
    xp_config = models.CharField(max_length=2000,unique=True)
    xp_cfg_name = models.CharField(max_length=200,null=True,blank=True)
    score_max = models.IntegerField(default=500)
    def __str__(self):
        return self.xp_config

class Experiment(models.Model):
    xp_config = models.ForeignKey(XpConfig, on_delete=models.PROTECT)
    xp_uuid = models.CharField(max_length=200,default='')
    user_agent_uuid = models.CharField(max_length=200,default='')
    interaction_counter = models.IntegerField(default=0)
    max_interaction = models.IntegerField(default=50)
    exit_value = models.FloatField(default=0)
    meanings = models.ManyToManyField(Meaning,related_name='meanings')
    words = models.ManyToManyField(Word,related_name='words')
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    last_ms = models.ForeignKey(Meaning, on_delete=models.PROTECT,related_name='last_ms',null=True)#,blank=True)
    last_mh = models.ForeignKey(Meaning, on_delete=models.PROTECT,related_name='last_mh',null=True)#,blank=True)
    last_w = models.ForeignKey(Word, on_delete=models.PROTECT,related_name='last_w',null=True)#,blank=True)
    last_role = models.CharField(max_length=200,default='')
    last_bool_succ = models.BooleanField(default=False)
    last_nb_skipped = models.IntegerField(default=0)
    size = models.IntegerField(default=1)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    completed_at = models.DateTimeField(blank=True,null=True,default=null_date)
    game_won = models.BooleanField(default=False)

    #Has the player seen the informations on the experiment before this game ?
    before_info = models.BooleanField(default=False)
    #Experiment number for the user
    xp_number = models.IntegerField(default=-1)
    #For the Admin interface
    is_complete = models.BooleanField(default = False)

    def __str__(self):
        return str(self.xp_uuid) + ' ' + str(self.xp_config.xp_config)

    def score(self):
        try:
            return Score.objects.get(experiment=self).score
        except:
            return None

    def init_xp(self):
        db = ngal.ngdb.NamingGamesDB(db_type='psycopg2',conn_info="host='db' dbname='naminggames' user='naminggames' password='naminggames'")
        self.xp = db.get_experiment(force_new=True,db_type='postgres',conn_info="host='db' dbname='naminggames' user='naminggames' password='naminggames'",**json.loads(self.xp_config.xp_config))
        self.xp_uuid = self.xp.uuid
        self.xp.init_poplist()
        self.xp._poplist.compress()
        #self.xp.continue_exp_until(0)
        #self.xp.commit_to_db()
        self.save()

        self.update_words()
        self.update_meanings()
        self.get_user_agent_uuid()
        self.xp._poplist.compress()
        self.xp.commit_to_db()
        self.save()

        u_ng = UserNG.objects.get(user=self.user)
        u_ng.last_xp = self.xp_uuid
        u_ng.save()

    def save(self,*args,**kwargs):
        # self.update_size()
        return models.Model.save(self,*args,**kwargs)

    # def update_size(self):
    #     ag_list = Agent.objects.filter(xp=self)
    #     if ag_list:
    #         self.size = len(ag_list) + 1
    #     else:
    #         xp_obj = self.get_xp()
    #         self.size = xp_obj._poplist.get_last().get_size()

    def delete(self):
        xp = self.get_xp()
        xp.clean_all()
        models.Model.delete(self)

    def get_xp(self):
        if not hasattr(self,'xp'):
            db = ngal.ngdb.NamingGamesDB(db_type='psycopg2',conn_info="host='db' dbname='naminggames' user='naminggames' password='naminggames'")
            self.xp = db.get_experiment(xp_uuid=self.xp_uuid)
        return self.xp

    @classmethod
    def get_new_xp(cls,user,xp_cfg_name="normal"):
        xp_cfg_temp = copy.deepcopy(xp_cfg)
        if xp_cfg_name == "basic":
            size = 3
            xp_cfg_temp["pop_cfg"]["nbagent"] = 3
            xp_cfg_temp["pop_cfg"]["env_cfg"]["M"] = 2
            xp_cfg_temp["pop_cfg"]["env_cfg"]["W"] = 6
            max_inter = 10
        elif xp_cfg_name == "normal":
            size = 5
            M = 5
            xp_cfg_temp["pop_cfg"]["nbagent"] = size
            xp_cfg_temp["pop_cfg"]["env_cfg"]["M"] = M
            xp_cfg_temp["pop_cfg"]["env_cfg"]["m_list"] = Meaning.get_mlist(M=M,avoid_if_possible=[0,1])
            xp_cfg_temp["pop_cfg"]["env_cfg"]["W"] = 6
            max_inter = 50
        elif xp_cfg_name == "multiuser":
            size = 1
            M = 5
            xp_cfg_temp["pop_cfg"]["nbagent"] = size
            xp_cfg_temp["pop_cfg"]["env_cfg"]["M"] = M
            xp_cfg_temp["pop_cfg"]["env_cfg"]["m_list"] = Meaning.get_mlist(M=M,avoid_if_possible=[0,1])
            xp_cfg_temp["pop_cfg"]["env_cfg"]["W"] = 6
            max_inter = 50
        if UserNG.objects.get(user=user).code == 'locust_test':
            xp_cfg_temp["pop_cfg"]["env_cfg"]["w_list"] = ['locust'+str(i) for i in range(xp_cfg_temp["pop_cfg"]["env_cfg"]["W"])]

        xp_cfg_json = json.dumps(xp_cfg_temp)
        xpcfg_list = XpConfig.objects.filter(xp_config=xp_cfg_json)
        if xpcfg_list:
            xp_conf_model = xpcfg_list.first()
        else:
            xp_conf_model = XpConfig(xp_config=xp_cfg_json,xp_cfg_name=xp_cfg_name,score_max=100*xp_cfg_temp["pop_cfg"]["env_cfg"]["M"])
            xp_conf_model.save()
        xp = Experiment(xp_config=xp_conf_model,user=user,max_interaction=max_inter,size=size)
        xp.init_xp()
        # if xp_cfg_name == 'multiuser':
        #     for i in range(4):
        #         ag = Agent.create()

ng/forms.py
from django import forms
from django.utils.translation import ugettext_lazy

class NameForm(forms.Form):
    your_name = forms.CharField(label='', max_length=100)
    name_cookie_id = forms.CharField(widget=forms.HiddenInput())
    lang = forms.CharField( max_length = 4, widget=forms.HiddenInput())
    code = forms.CharField(max_length=100, required=False)

class QuestionForm(forms.Form):
    CHOICES = ((True,ugettext_lazy('Yes')), (False,ugettext_lazy('No')))
    q0 = forms.TypedChoiceField(
        label="",
        required=True,
        widget=forms.RadioSelect,
        choices= ((-1,ugettext_lazy('Frustrated')), (0,ugettext_lazy('Neutral')), (1,ugettext_lazy('I enjoyed it')), ),
    )
    q1 = forms.TypedChoiceField(
        label="",
        required=True,
        widget=forms.RadioSelect,
        choices= CHOICES,
    )
    q2 = forms.TypedChoiceField(
        label="",
        required=True,
        widget=forms.RadioSelect,
        choices= CHOICES,
    )
    q3 = forms.TypedChoiceField(
        label="",
        required=True,
        widget=forms.RadioSelect,
        choices= CHOICES,
    )
    q4 = forms.TypedChoiceField(
        label="",
        required=True,
        widget=forms.RadioSelect,
        choices= CHOICES,
    )
    q5 = forms.CharField(label="",required=False,widget=forms.Textarea)
    q6 = forms.CharField(label="",required=False,widget=forms.Textarea)

ng/templates/ng/col1.html
 {% load static %}
{% load i18n %}

 <div class="col_1 col">
          <div class="imag_center">
          <img src="{% static  'ng/img/n_ghome.png' %}" id="home" style="pointer:cursor;width:40px;">

        </div>
        <div class="imag_center_two">
<!--           <img id='you_fr' src="{% static  'ng/img/chat-min.png' %}" style="display: none">
          <img id='you_en' src="{% static  'ng/img/chat_you.png' %}" style="width:68px"> -->
<img id="you" src={% trans "/static/ng/img/chat_you.png" %} style="width:68px">
        </div>
        <div class="imag_center_twot_tru">
          {% if experiment.size == 3 %}
          <img id="groop_3" src="{% static  'ng/img/user_groop.png' %}">
          {% else %}
          <img id="groop_5" src="{% static  'ng/img/user_groop5.png' %}">
          {% endif %}

        </div><!--
        <img src="{% static  'ng/img/soundon.png' %}" id="sound-on" style= "margin: 1px auto 4px; padding-left: 25px;">
        <img src="{% static  'ng/img/soundoff.png' %}" id="sound-off" style= "margin: 1px auto 4px; padding-left: 25px;"> -->
        </div>

ng/templates/ng/login_name.html
{% load static %}
{% load i18n %}

<!DOCTYPE html>
<html lang="fr">
  <head>
    <meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title id="window_title">Naming Game</title>
    <!-- Bootstrap CSS -->
    <link type="text/css" rel="stylesheet" href="{% static 'ng/bootstrap-4.0.0-dist/css/bootstrap.min.css' %}"/>
    <link type="text/css" rel="stylesheet" href="{% static 'ng/bootstrap-3.3.7-dist/css/bootstrap.min.css' %}"/>

  	<!--CSS-->
  	<link type="text/css" rel="stylesheet" href="{% static 'ng/ng.css' %}"/>

  	<!--JQuery-->
    <!--<script src="{% static 'ng/jquery-3.2.1.min.js' %}"></script>-->
  	<script src="{% static 'ng/jquery-3.3.1.min.js' %}"></script>
  	<script src="{% static 'ng/popper.min.js' %}"></script>
  	<script src="{% static 'ng/bootstrap.min.js' %}"></script>
    <script src="{% static 'ng/js.cookie.js' %}"></script>
    <script src="{% static 'ng/script.js' %}"></script>
    <script src="{% static 'ng/lang.js' %}"></script>
    <script src="{% static 'ng/change_lang.js' %}"></script>

	  <!--  <script src="{% static 'ng/login.js' %}"></script> -->
     <script type="text/javascript">
         var url_send_user_info = "{% url 'ng:send_user_info_base'  %}";
         var url_newxp = "{% url 'ng:new_experiment'  %}";
         var url_home = "{% url 'ng:home'  %}";

         var sound_click = document.createElement('audio');
         sound_click.setAttribute('src', "{% static 'ng/sounds/60945__erh__click.wav' %}");
         Cookies.set('NamingGameSound', true);

         //uuid
         function uuid()
         {
             return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, function(c) {
                 var r = Math.random()*16|0, v = c === 'x' ? r : (r&0x3|0x8);
                 return v.toString(16);
             });
         }

         //user cookie
         if (typeof Cookies.get('NamingGameUser') === 'undefined'){
             var user_str = uuid();
             $("#username").html(user_str);
             Cookies.set('NamingGameUser',
                 user_str
                 );
             };

          //language
         $(".info_lang").click(function(){
            sound_click.play();
            var language = $(this).val();
            $('#lang').html(language);
            $("#id_lang").val($("#lang").html());
          });

          $('#submit').click(function(){
            sound_click.play();
          });


          $(document).ready(function(){

            $('body').css('visibility', 'visible');

            $("#id_name_cookie_id").val($("#username").html());

            $('#id_code').tooltip({
              title : "",
              placement : "left",
              trigger : "hover focus",
            });


            $('#it').click(function(event){
                change_language(($('#it').attr('value')));
                $('#id_code').attr('data-original-title', "ITALIAN");
            });
            $('#en').click(function(event){
                change_language(($('#en').attr('value')));
                $('#id_code').attr('data-original-title', "If you don't have any code, leave this field empty.");
            });
            $('#fr').click(function(event){
                change_language(($('#fr').attr('value')));

                $('#id_code').attr('data-original-title', "Si vous n'avez pas de code, laissez ce champ vide.");

            });
            set_language();

            });


     </script>

     <!--<form method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit" />
</form>-->
 {% include "ng/matomo.html" %}
  </head>
<body>
	<h1 class="pagetitle" style="padding:0px; margin-top:25px;" id="welcome">Le Naming Game !</h1>
	<!-- Formulaire -->
	 <!--action="/action_page.php"-->
	<form id="form" method="post">
		<div class="form-group">

    			<div class="row">
				<div class="col-md-4"> </div>
				<div class="col-md-4">
					<!--Choix Nom-->


				<!--	<input type="username" class="form-control" id="username" value="Submit" required>-->
<!-- 				{% csrf_token %} -->

			{% csrf_token %}
      {{form.non_field_errors}}
      <div class="fieldWrapper">
      {{ form.name_cookie_id.errors }}
      {{ form.name_cookie_id }}
      </div>

      <div class="fieldWrapper">
        {{ form.your_name.errors }}
        <label for="player-name" class="label1" id="enter_player_name" style="display:block">Entrez votre nom ici :</label>
				{{ form.your_name }}
      </div>

          <div class="not_displayed" style= "visible:hidden; display:none">
            <span id="username"></span>
          </div>
				</div>
				<div class="col-md-4"> </div>
			</div>
      <div class="fieldWrapper">
      {{ form.name_lang.errors }}
      {{ form.name_lang }}
      </div>
				<!--Choix Langage-->
				<label class="label1" id="label_lang">Choisissez la langue du jeu :</label>

			<div class="row" id="middle">
        <div class="col-lg-2 visible-lg"> </div>
				<div class="col-lg-2 col-xs-12">
					<label class = "lang">
  						<input type="radio"  name="lang" class="info_lang"  id="fr" value="fr"  checked/>
						<!--adresse img :https://cdn.pixabay.com/photo/2015/11/20/18/55/french-flag-1053711_960_720.png-->
						<img src="{% static 'ng/img/french-flag.png' %}"  class="lang" value="fr" for="fr" alt="french" width= 160px height= 115px >
					</label>
				</div>

				<div class="col-lg-4 col-xs-12">
					<label class="lang">
  						<input type="radio" class="lang" name="lang" class="info_lang" id="en" value="en"/>
						<!--adresse img :https://cdn.pixabay.com/photo/2012/04/23/16/15/flags-38754_960_720.png-->
						<img src="{% static 'ng/img/english-flag.png' %}" class="lang" value="en" for="en" alt="english" width= 160px height= 115px >
					</label>
				</div>
				<div class="col-lg-2 col-xs-12">
					<label class="lang">
  						<input type="radio" class="lang" name="lang" class="info_lang" id="it" value="it" />
						<!--adresse img :https://cdn.pixabay.com/photo/2012/04/11/15/35/flag-28543_960_720.png-->
						<img src="{% static 'ng/img/italian-flag.png' %}" class="lang" value="it" for = "it" alt="italian" width= 160px height= 125px >
					</label>
				</div>
        <div class="col-lg-2 visible-lg"> </div>
			</div>

      <div class="row">
        <!--Code si pertinent-->
        <div class="col-md-4"> </div>
        <div class="col-md-4">
          <div class="fieldWrapper">
              {{form.code.errors}}
              <label class="label1" id="label_code" style= "font-size: 20px;">Si vous avez un code spécial, veuillez l'entrer ici :</label>
              {{form.code}}
          </div>
      </div>
      <div class="col-md-4"></div>
      </div>

			<div class="row" id="footer">
				<div class="col-md-4"> </div>
				<div class="col-md-4">

					<input type="submit" class="btn btn-default bt-lg" id="submit" value="Valider"/>

				</div>
				<div class="col-md-4"></div>
			</div>
		</div>
	</form>


{% csrf_token %}
  </body>

  <div class="not_displayed">
    <span id="username"></span>
    <span id="lang"></span>
</div>

</html>